// frontend/src/pages/user/components/UserSidebar.tsx
import * as React from "react";
// page
import { Package, LayoutDashboard } from "lucide-react";
import { NavUser } from "@/components/nav-user";
import {
  Sidebar,
  SidebarHeader,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
} from "@/components/ui/sidebar";

// auth -> contentxt
import { useAuth } from "@/app/AuthContext";

// router
import { Link } from "@tanstack/react-router";

const navItems = [
  {
    name: "Dashboard",
    url: "/userpanel/userDashboard",
    icon: LayoutDashboard,
  },
  {
    name: "Products",
    url: "/userpanel/userProduct",
    icon: Package,
  },
];

export function UserSidebar(props: React.ComponentProps<typeof Sidebar>) {
  const { user } = useAuth();
  if (!user) return null;

  const userInfo = {
    email: user.email,
    username: user.username ?? "User",
    avatar: user.avatar ?? "",
  };

  return (
    <Sidebar collapsible="offcanvas" {...props}>
      <SidebarHeader>
        <Link
          to="/"
          className="flex items-center px-3 py-2 hover:opacity-80 transition-opacity cursor-pointer"
        >
          <h1 className="text-xl font-extrabold tracking-tight">
            KIRA <span className="text-neutral-500">Inventory</span>
          </h1>
        </Link>
      </SidebarHeader>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupLabel>Free</SidebarGroupLabel>
          <SidebarMenu>
            {navItems.map((item) => (
              <SidebarMenuItem key={item.name}>
                <SidebarMenuButton asChild>
                  <Link to={item.url}>
                    <item.icon />
                    <span>{item.name}</span>
                  </Link>
                </SidebarMenuButton>
              </SidebarMenuItem>
            ))}
          </SidebarMenu>
        </SidebarGroup>
      </SidebarContent>
      <SidebarFooter>
        <NavUser user={userInfo} />
      </SidebarFooter>
    </Sidebar>
  );
}

// svelte/src/lib/components/user/UserSidebar.svelte
<script lang="ts">
  import { Package, LayoutDashboard } from '@lucide/svelte';
  import NavUser from '$lib/components/nav-user.svelte';
  import {
    Sidebar,
    SidebarHeader,
    SidebarContent,
    SidebarFooter,
    SidebarGroup,
    SidebarGroupLabel,
    SidebarMenu,
    SidebarMenuItem,
    SidebarMenuButton,
  } from '$lib/components/ui/sidebar';

  // temporary mock data (UI only)
  const userInfo = {
    email: 'demo@example.com',
    username: 'DemoUser',
    avatar: '/placeholder.svg',
  };

  const navItems = [
    { name: 'Dashboard', url: '/userpanel/userDashboard', icon: LayoutDashboard },
    { name: 'Products', url: '/userpanel/userProduct', icon: Package },
  ];
</script>

<Sidebar collapsible="offcanvas" variant="inset">
  <SidebarHeader>
    <a
      href="/"
      class="flex cursor-pointer items-center px-3 py-2 transition-opacity hover:opacity-80"
    >
      <h1 class="text-2xl font-extrabold tracking-tight">
        KIRA <span class="text-neutral-600">Inventory</span>
      </h1>
    </a>
  </SidebarHeader>

  <SidebarContent>
    <SidebarGroup>
      <SidebarGroupLabel>Free</SidebarGroupLabel>
      <SidebarMenu>
        {#each navItems as item (item.name)}
          <SidebarMenuItem>
            <SidebarMenuButton class="cursor-pointer text-neutral-500">
              <a href={item.url} class="flex items-center gap-2">
                <svelte:component this={item.icon} />
                <span>{item.name}</span>
              </a>
            </SidebarMenuButton>
          </SidebarMenuItem>
        {/each}
      </SidebarMenu>
    </SidebarGroup>
  </SidebarContent>

  <SidebarFooter>
    <NavUser user={userInfo} />
  </SidebarFooter>
</Sidebar>
